---
- name: Provision EC2 instance in Mumbai region
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-south-1
    instance_type: t2.micro
    ami_id: ami-0b08bfc6ff7069aff
    keypair: devops
    security_group: my-security-group
  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group }}"
        description: Security Group for Web Servers
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 9000
            to_port: 9000
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 9090
            to_port: 9090
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: ec2_security_group

    - name: Launch EC2 instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ region }}"
        count: 1
        wait: yes
        instance_tags:
          Name: my-ec2-instance
        metadata_options:
          http_endpoint: enabled
          http_tokens: required
      register: ec2_instance

    - name: Print instance details
      debug:
        var: ec2_instance.instances
