version: '3.1'
services:
  DB:
    container_name: db
    image: mysql:latest
    build: ./db-dump/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d